# Generated by Django 4.0.6 on 2022-08-28 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='orgs.organisation')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='A short title summarising your report.', max_length=255)),
                ('description', models.TextField(help_text='A description of what happened.')),
                ('photo_1', models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Photo 1 (Optional)')),
                ('photo_2', models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Photo 2 (Optional)')),
                ('photo_3', models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Photo 3 (Optional)')),
                ('status', django_fsm.FSMField(default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbacks.category')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='orgs.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='internal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.feedback')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
