# Generated by Django 4.0.6 on 2022-08-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.TextField(help_text='A short title summarising your report.'),
        ),
    ]
