# Generated by Django 4.0.6 on 2022-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='categories',
            field=models.ManyToManyField(blank=True, to='feedbacks.category'),
        ),
    ]
