# Generated by Django 4.0.6 on 2022-07-25 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbacks', '0002_remove_feedback_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
