# Generated by Django 4.0.6 on 2022-08-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedback_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='categories',
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbacks.category'),
        ),
    ]
