# Generated by Django 4.0.6 on 2022-07-25 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('feedbacks', '0003_alter_feedback_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='orgs.organisation')),
            ],
        ),
    ]
