# Generated by Django 4.0.6 on 2022-07-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('feedbacks', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='orgs.organisation'),
        ),
    ]
