# Generated by Django 4.0.6 on 2022-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
